# Generated by Django 4.2.1 on 2023-05-25 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=uuid.UUID('4b3d837f-b0ff-4fe0-b929-7e84025771ab'))),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=20)),
                ('book_published_on_date', models.DateField()),
                ('book_price', models.IntegerField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
