# Generated by Django 4.2.1 on 2023-05-25 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_books_book_author_alter_books_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
